### ISSUE TITLE
Error in action template

### ISSUE THREAD

**Issue by nspyke** [Azure/container-apps-deploy-action#25]
When running this action with the following config
```yaml
      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@v0
        with:
          containerAppName: ${{ env.CONTAINER_NAME }}
          resourceGroup: rg-workloads-container-apps-stg
          containerAppEnvironment: cae-workloads-external-stg
          location: australiaeast
          imageToDeploy: ${{ env.ACR_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ needs.build.outputs.version }}
          acrUsername: ${{ env.ACR_USERNAME }}
          acrPassword: ${{ secrets.ACR_PASSWORD }}
          environmentVariables: |
            ConnectionStrings__Foo=${{ env.CONNECTION_STRING }}
```

I get these errors on job initialization (set up job).
```
Error: azure/container-apps-deploy-action/v0/action.yml (Line: 275, Col: 11):
Error: azure/container-apps-deploy-action/v0/action.yml (Line: [27](https://github.com/xxx/yyyyy/actions/runs/4154099689/jobs/7186257819#step:1:31)5, Col: 11):
Error: azure/container-apps-deploy-action/v0/action.yml (Line: 275, Col: 11): Unexpected symbol: '&&'. Located at position 57 within expression: runner.os == 'Windows' && inputs.appSourcePath != '' && && env.CA_GH_ACTION_DOCKERFILE_PATH == ''
Error: azure/container-apps-deploy-action/v0/action.yml (Line: 275, Col: 11): Unexpected symbol: '${{'. Located at position 1 within expression: ${{ runner.os == 'Windows' && inputs.appSourcePath != '' && && env.CA_GH_ACTION_DOCKERFILE_PATH == '' }}
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. azure/container-apps-deploy-action/v0/action.yml (Line: 275, Col: 11): Unexpected symbol: '&&'. Located at position 57 within expression: runner.os == 'Windows' && inputs.appSourcePath != '' && && env.CA_GH_ACTION_DOCKERFILE_PATH == '',azure/container-apps-deploy-action/v0/action.yml (Line: 275, Col: 11): Unexpected symbol: '${{'. Located at position 1 within expression: ${{ runner.os == 'Windows' && inputs.appSourcePath != '' && && env.CA_GH_ACTION_DOCKERFILE_PATH == '' }}
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load azure/container-apps-deploy-action/v0/action.yml
```

Is this an error with my template or this action?

**Comment by marviobezerra** [comment]
I'm getting the same error and it's really blocking my team.

**Comment by rubenmamo** [comment]
I'm getting the same error. @marviobezerra you can get your workflow working again by targetting the previous version:
```
uses: azure/container-apps-deploy-action@47e03a783248cc0b5647f7ea03a8fb807fbc8e2f
```

**Comment by danielmellqvist** [comment]
Same here, I'm getting the same error.

**Comment by larsmak** [comment]
We're also getting this - after specifying an existing containerAppEnvironment, it was working prior to this.

**Comment by danielmellqvist** [comment]
The error message seems to suggest that there's a simple solution. Remove one of the && on line 275 in the file action.yml.

![image](https://user-images.githubusercontent.com/62037846/218488192-67abd354-efb0-4d5b-8cf7-2f3590643db8.png)

**Comment by cormacpayne** [comment]
Hey folks, apologies for this issue -- this has been resolved and the fix is now live in version `v0` of the action.
